---
- name: Ensure business databases
  community.mysql.mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default(mysql_collation_server) | default('utf8mb4_general_ci') }}"
    encoding: "{{ item.encoding | default(mysql_character_set_server) | default('utf8mb4') }}"
    single_transaction: "{{ item.single_transaction | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ mysql_databases }}"
  when:
    - mysql_databases|length > 0
