---
- name: Import check vars tasks
  ansible.builtin.import_tasks:
    file: check_vars.yaml
  when:
    - inventory_hostname in groups[mysql_inventory_group]
  tags:
    - always
    - check

- name: Import prepare tasks
  ansible.builtin.import_tasks:
    file: prepare.yaml
  tags:
    - always
    - prepare

- name: Include install jemalloc tasks
  ansible.builtin.include_tasks:
    file: install_jemalloc.yaml
  when:
    - ansible_architecture in ['aarch64']
    - ansible_distribution_major_version in ['7']
    - ansible_os_family in ['RedHat']
  tags:
    - always
    - install

- name: Include install tasks
  ansible.builtin.include_tasks:
    file: install.yaml
  when:
    - inventory_hostname in groups[mysql_inventory_group]
  tags:
    - always
    - install

- name: Include mysql shell tasks
  ansible.builtin.include_tasks:
    file: mysql_shell.yaml
    apply:
      tags:
        - shell
  when:
    - mysql_cluster_type == 'mgr'
    - mysql_innodb_cluster_enable|bool
    - inventory_hostname in groups[mysql_inventory_group]
  tags:
    - always

- name: Include replication tasks
  ansible.builtin.include_tasks:
    file: master_slave.yaml
    apply:
      tags:
        - ms
        - rs
  when:
    - mysql_cluster_type == 'ms'
    - inventory_hostname in groups[mysql_inventory_group]
  tags:
    - always

- name: Import create database tasks
  ansible.builtin.import_tasks:
    file: create_database.yaml
  run_once: true
  delegate_to: "{{ _primary_node }}"

- name: Import create user tasks
  ansible.builtin.import_tasks:
    file: create_user.yaml
  run_once: true
  delegate_to: "{{ _primary_node }}"

- name: import mha4mysql common tasks
  ansible.builtin.include_tasks:
    file: mha4mysql_common.yaml
    apply:
      tags:
        - mha
  when:
    - mysql_cluster_type == 'ms'
    - mysql_mha_enabled | bool
  tags:
    - always

- name: import mha4mysql node tasks
  ansible.builtin.include_tasks:
    file: mha4mysql_node.yaml
    apply:
      tags:
        - mha
  when:
    - mysql_cluster_type == 'ms'
    - mysql_mha_enabled | bool
    # - inventory_hostname in groups[mysql_inventory_group]
  tags:
    - always
    - mha-node

- name: import mha4mysql manager tasks
  ansible.builtin.include_tasks:
    file: mha4mysql_manager.yaml
    apply:
      tags:
        - mha
        - manager
  when:
    - mysql_mha_enabled | bool
    - inventory_hostname in groups['mha_manager']
  tags:
    - always
    - mha-manager
