---
- name: Stop group replication
  community.mysql.mysql_query:
    query: STOP GROUP_REPLICATION

- name: Restart mysqld service
  systemd:
    name: mysqld.service
    state: restarted
    daemon_reload: true

- name: Watting for mysqld service restarted
  wait_for:
    path: "{{ mysql_socket }}"
    state: started

- name: Start group replication
  community.mysql.mysql_query:
    query: START GROUP_REPLICATION
