---
- name: Cleanup
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Find downloaded packages
      ansible.builtin.find:
        path: '{{ playbook_dir }}/files'
        patterns: '*.tar.*,*.rpm'
        file_type: file
      register: __find_packages

    - name: Cleanup packages
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: absent
      loop: '{{ __find_packages.files }}'
