---
- name: Converge
  hosts: all
  any_errors_fatal: yes
  tasks:
    - name: Include epel role
      ansible.builtin.include_role:
        name: daixijun.epel
      when:
        - ansible_os_family == 'RedHat'

    - name: Include mysql role
      ansible.builtin.include_role:
        name: mysql
        apply:
          tags:
            - always
      vars:
        mysql_cluster_type: ms
        mysql_root_password: ieng8Taibonga6dair0j
        mysql_repl_password: Ad5sa7aer7eiN3goo2be
        mysql_group_replication_name: cdbdc06c-2023-4d20-9821-272f160ef4f6
        mysql_databases:
          - name: db1
        mysql_users:
          - name: user1
            password: Ang4eij~aiSh4lu4tho5
            priv: 'db1.*:ALL'
