---
dependency:
  name: galaxy
driver:
  name: docker
# lint: |
#   set -e
#   ansible-lint -v
platforms:
  - name: mysql1
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - mysql
provisioner:
  name: ansible
  inventory:
    group_vars:
      mysql:
        mysql_download_url: ${MOLECULE_MYSQL_DOWNLOAD_URL}
  config_options:
    defaults:
      verbosity: 2
      vault_password_file: ${MOLECULE_SCENARIO_DIRECTORY}/vault.pw
verifier:
  name: ansible
