---
dependency:
  name: galaxy
  # options:
  #   role-file: molecule/requirements.yml
  #   requirements-file: molecule/requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint -v
platforms:
  - name: mysql1
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - mysql
    children:
      - mysql_primary
  - name: mysql2
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    purge_networks: false
    groups:
      - mysql
    children:
      - mysql_secondary
  - name: mysql3
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    purge_networks: false
    groups:
      - mysql
    children:
      - mysql_secondary
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATHS: /home/runner/.ansible/collections:~/.ansible/collections:/usr/share/ansible/collections
  ansible_args:
    - "--extra-vars=mysql_version=${MYSQL_VERSION:-8.0.20}"
  config_options:
    defaults:
      verbosity: 2
      vault_password_file: ${MOLECULE_SCENARIO_DIRECTORY}/vault.pw
      collections_paths: /home/runner/.ansible/collections:~/.ansible/collections:/usr/share/ansible/collections
verifier:
  name: ansible
