---
- name: Converge
  hosts: all
  any_errors_fatal: yes
  tasks:
    - name: Include mysql role
      include_role:
        name: mysql
        apply:
          tags:
            - always
      vars:
        mysql_cluster_type: ms
        mysql_root_password: ieng8Taibonga6dair0j
        mysql_repl_password: Ad5sa7aer7eiN3goo2be
        mysql_databases:
          - name: db1
        mysql_users:
          - name: user1
            password: Ang4eij~aiSh4lu4tho5
            priv: 'db1.*:ALL'
